#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

# Programmer: Monil Gandhi


# Load modules
module load python2 samtools/0.1.19 bowtie2 boost tophat

# TopHat command
tophat -r 200 -G /project/bf528/project_2/reference/annot/mm9.gtf --segment-length=20 --segment-mismatches=1 --no-novel-juncs -o P0_1_tophat -p 16 /project/bf528/project_2/reference/mm9 /projectnb/bf528/users/van-gogh/project_2/data/P0_1_1.fastq /projectnb/bf528/users/van-gogh/project_2/data/P0_1_2.fastq 

echo "Job finished: $(date +%F)"				   
