#!/bin/bash -l

#$ -P bf528
#$ -cwd
#$ -j y
#$ -pe mpi_16_tasks_per_node 16

# Programmer: Monil Gandhi

echo "Running job $JOB_ID"
echo "Started: $(date +%F)"
echo "Running in directory: $PWD"

# Load modules
module unload anaconda3
module load python3 samtools rseqc

# RseQC utilities
geneBody_coverage.py -i P0_1_tophat/accepted_hits.bam -r /project/bf528/project_2/reference/annot/mm9.bed -o geneBody
inner_distance.py -i P0_1_tophat/accepted_hits.bam -r /project/bf528/project_2/reference/annot/mm9.bed -o inner_distance
bam_stat.py -i P0_1_tophat/accepted_hits.bam > bam_stat.txt

echo "Job finished: $(date +%F)"
